
server.port=5054

spring.application.name=PROJECT-MANAGEMENT


###### Connect app to database :- ######

#spring.datasource.url= ${db_URL}
spring.datasource.username = ${db_USERNAME}
spring.datasource.password = ${db_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:h2:mem:Manager
spring.datasource.driverClassName = org.h2.Driver
spring.h2.console.enabled = true


###### JPA and Hibernate config (while handling database) :- ######

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.properties.hibernate.format_sql = true
logging.level.org.hibernate.orm.jdbc.bind = trace


####### Java mail service (using Gmail SMTP) :- ######

# ___SMTP Host (e.g. Gmail)
spring.mail.host = ${MAIL_HOST}
spring.mail.port = ${MAIL_PORT}

# ___email credentials
spring.mail.username = ${MAIL_USERNAME}
spring.mail.password = ${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


###### API keys :- ######
razorpay.api.key = ${RAZORPAY_API_KEY}
razorpay.api.secret = ${RAZORPAY_SECRET_KEY}